/**
 * @summary
 * Application error codes
 */
export enum ErrorCode {
  // Authentication errors
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  
  // Validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  
  // Counter errors
  COUNTER_ALREADY_RUNNING = 'COUNTER_ALREADY_RUNNING',
  COUNTER_NOT_RUNNING = 'COUNTER_NOT_RUNNING',
  COUNTER_ALREADY_PAUSED = 'COUNTER_ALREADY_PAUSED',
  COUNTER_NOT_PAUSED = 'COUNTER_NOT_PAUSED',
  
  // Server errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
}
